# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0002_develop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='develop',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
