# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='develop',
            name='slug',
            field=models.SlugField(default='asdas', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
