# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import private_media.storages
import vre.apps.documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=private_media.storages.PrivateMediaStorage(), upload_to=vre.apps.documents.models.get_file_path, verbose_name='File'),
        ),
    ]
