# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import vre.apps.documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0003_auto_20160709_1118'),
        ('documents', '0002_auto_20160710_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=vre.apps.documents.models.get_file_path_brochuere, verbose_name='File')),
                ('develop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developments.Develop', verbose_name='Develop')),
            ],
            options={
                'verbose_name': 'Brochure',
                'verbose_name_plural': 'Brochures',
            },
        ),
    ]
