# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user_type',
            field=models.CharField(choices=[(b'client', 'Client'), (b'investor', 'Investor')], default=b'client', max_length=20, verbose_name='User type'),
        ),
    ]
