# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Susucriber',
                'verbose_name_plural': 'Suscribers',
            },
        ),
    ]
