# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20160809_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='source',
            field=models.CharField(default='contact', max_length=50, verbose_name='Source'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
    ]
