# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooluser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates that this user is active to login the plataform', verbose_name='Active'),
        ),
    ]
