# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160709_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooluser',
            name='developments',
            field=models.ManyToManyField(to='developments.Develop', verbose_name='Developments'),
        ),
    ]
