# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160802_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooluser',
            name='is_admin',
        ),
    ]
